import type { Metadata } from "next";
import Navbar from "./componens/navbar";
import "./globals.css";
import Hamburger from "./componens/hamburger-spin";

export const metadata: Metadata = {
  title: "Create NextJs Astro",
  description: "Generated by create next app",
  icons: {
    icon: "/saturn.png", // Alapértelmezett favicon
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="hu">
      <body className="min-h-screen bg-no-repeat bg-cover bg-center"
        style={{ backgroundImage: "url('/galaxy.jpg')" }}>
        <main >
          <Navbar />
          <Hamburger />
          {children}
        </main>
      </body>
    </html>
  );
}
